# Use the official Ubuntu image
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
        wget \
        expect \
        curl \
        ca-certificates \
        bash \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

# Add the shell script to the container
ADD win.sh /usr/local/bin/win.sh

# Make the script executable
RUN chmod +x /usr/local/bin/win.sh

# Set the entry point to run the script
ENTRYPOINT ["/usr/local/bin/win.sh"]

# Provide default arguments for the script
CMD ["-b", "win"]
